# Generated by Django 2.0.3 on 2019-03-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('scoops_remaining', models.IntegerField(choices=[(0, 'zero'), (1, 'one')], default=0)),
            ],
        ),
    ]
